dist: trusty
language: java
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - set -e
  - ./gradlew check
  - ./gradlew codeCoverageReport
  - ./gradlew build assemble && ./docker-build.sh
  - set +e
after_success:
  - bash <(curl -s https://codecov.io/bash) -f build/reports/jacoco/report.xml
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/